from RedditClient import RedditClient

class RedditSubreddit(RedditClient):

    def __init__(self):
        self.where = None
        self.subreddit = None

        self.after = None
        self.before = None
        self.count = None
        self.limit = None
        self.show = None
        self.sr_detail = None
        self.user = None
        self.uh_x_modhash_header = None
        self.api_type = 'json'
        self.img_name = None
        self.omit = None
        self.over_18 = None
        self.srnames = None
        self.include_over_18 = None
        self.include_unadvertisable = None
        self.query = None
        self.search_query_id = None
        self.typehead_active = None
        self.exact = None
        self.admin_override_spam_comments = None
        self.admin_override_spam_links = None
        self.admin_override_spam_selfposts = None
        self.all_original_content = None
        self.allow_chat_post_creation = None
        self.allow_discovery = None
        self.allow_galleries = None
        self.allow_images = None
        self.allow_polls = None
        self.allow_post_crossposts = None
        self.allow_predictions = None
        self.allow_predictions_tournaments = None
        self.allow_top = None
        self.allow_videos = None
        self.api_type = None
        self.automated_reporting_level_abuse = None
        self.automated_reporting_level_hate = None
        self.collapse_deleted_comments = None
        self.comment_score_hide_mins = None
        self.crowd_control_chat_level = None
        self.crowd_control_level = None
        self.crowd_control_mode = None
        self.description = None
        self.disable_contributor_requests = None
        self.exclude_banned_modqueue = None
        self.free_form_reports = None
        self.g_recaptcha_response = None
        self.header_title = None
        self.hide_ads = None
        self.key_color = None
        self.lang = None
        self.link_type = None
        self.name = None
        self.new_pinned_post_pns_enabled = None
        self.original_content_tag_enabled = None
        self.over_18 = None
        self.prediction_leaderboard_entry_type = None
        self.public_description = None
        self.restrict_commenting = None
        self.restrict_posting = None
        self.show_media = None
        self.show_media_preview = None
        self.spam_comments = None
        self.spam_links = None
        self.spam_selfposts = None
        self.spoilers_enabled = None
        self.sr = None
        self.submit_link_label = None
        self.submit_text = None
        self.submit_text_label = None
        self.suggested_comment_sort = None
        self.title = None
        self.toxicity_threshold_chat_level = None
        self.type =  None
        self.user_flair_pns_enabled = None
        self.welcome_message_enabled = None
        self.welcome_message_text = None
        self.wiki_edit_age = None
        self.wiki_edit_karma = None
        self.wikimode = None
        self.include_profiles = None
        self.query = None
        self.op = None
        self.reason = None
        self.stylesheet_contents = None


    def generate_queries(self):

        body = {}

        if self.after != None:
            body['after'] = self.after
        if self.before != None:
            body['before'] = self.before
        if self.count != None:
            body['count'] = self.count
        if self.limit != None:
            body['limit'] = self.limit
        if self.show != None:
            body['show'] = self.show
        if self.sr_detail != None:
            body['sr_detail'] = self.sr_detail
        if self.user != None:
            body['user'] = self.user
        if self.uh_x_modhash_header != None:
            body['uh / X-Modhash header'] = self.uh_x_modhash_header
        if self.api_type != None:
            body['api_type'] = self.api_type
        if self.img_name != None:
            body['img_name'] = self.img_name
        if self.omit != None:
            body['omit'] = self.omit
        if self.over_18 != None:
            body['over_18'] = self.over_18
        if self.srnames != None:
            body['srnames'] = self.srnames
        if self.exact != None:
            body['exact'] = self.exact
        if self.include_over_18 != None:
            body['include_over_18'] = self.include_over_18
        if self.include_unadvertisable != None:
            body['include_unadvertisable'] = self.include_unadvertisable
        if self.query != None:
            body['query'] = self.query
        if self.search_query_id != None:
            body['search_query'] = self.search_query_id
        if self.typehead_active != None:
            body['typehead_active'] = self.typehead_active
        if self.admin_override_spam_comments != None:
            body['admin_override_spam_comments'] = self.admin_override_spam_comments
        if self.admin_override_spam_links != None:
            body['admin_override_spam_links'] = self.admin_override_spam_links
        if self.admin_override_spam_selfposts != None:
            body['admin_override_spam_selfposts'] = self.admin_override_spam_selfposts
        if self.all_original_content != None:
            body['all_original_content'] = self.all_original_content
        if self.allow_chat_post_creation != None:
            body['allow_chat_post_creation'] = self.allow_chat_post_creation
        if self.allow_discovery != None:
            body['allow_discovery'] = self.allow_discovery
        if self.allow_galleries != None:
            body['allow_galleries'] = self.allow_galleries
        if self.allow_images != None:
            body['allow_images'] = self.allow_images
        if self.allow_polls != None:
            body['allow_polls'] = self.allow_polls
        if self.allow_post_crossposts != None:
            body['allow_post_crossports'] = self.allow_post_crossposts
        if self.allow_predictions != None:
            body['allow_predictions'] = self.allow_predictions
        if self.allow_predictions_tournaments != None:
            body['allow_predictions_tournament'] = self.allow_predictions_tournaments
        if self.allow_top != None:
            body['allow_top'] = self.allow_top
        if self.allow_videos != None:
            body['allow_videos'] = self.allow_videos
        if self.api_type != None:
            body['api_type'] = 'json'
        if self.automated_reporting_level_abuse != None:
            body['automated_reporting_level_abuse'] = self.automated_reporting_level_abuse
        if self.automated_reporting_level_hate != None:
            body['automated_reporting_level_hate'] = self.automated_reporting_level_hate
        if self.collapse_deleted_comments != None:
            body['collapse_deleted_comments'] = self.collapse_deleted_comments
        if self.comment_score_hide_mins != None:
            body['comment_score_hide_mins'] = self.comment_score_hide_mins
        if self.crowd_control_chat_level != None:
            body['crowd_control_chat_level'] = self.crowd_control_chat_level
        if self.crowd_control_level != None:
            body['crowd_control_level'] = self.crowd_control_level
        if self.crowd_control_mode != None:
            body['crowd_control_mode'] = self.crowd_control_mode
        if self.description != None:
            body['description'] = self.description
        if self.disable_contributor_requests != None:
            body['disable_contributor_requests'] = self.disable_contributor_requests
        if self.exclude_banned_modqueue != None:
            body['exclude_banned_modqueue'] = self.exclude_banned_modqueue
        if self.free_form_reports != None:
            body['free_from_reports'] = self.free_form_reports
        if self.g_recaptcha_response != None:
            body['g-recaptcha-response'] = self.g_recaptcha_response
        if self.header_title != None:
            body['header-title'] = self.header_title
        if self.hide_ads != None:
            body['hide_ads'] = self.hide_ads
        if self.key_color != None:
            body['key_color'] = self.key_color
        if self.lang != None:
            body['lang'] = self.lang
        if self.link_type != None:
            body['link_type'] = self.link_type
        if self.name != None:
            body['name'] = self.name
        if self.new_pinned_post_pns_enabled != None:
            body['new_pinned_post_pns_enabled'] = self.new_pinned_post_pns_enabled
        if self.original_content_tag_enabled != None:
            body['original_content_tag_enabled'] = self.original_content_tag_enabled
        if self.over_18 != None:
            body['over_18'] = self.over_18
        if self.prediction_leaderboard_entry_type != None:
            body['prediction_leaderboard_entry_type'] = self.prediction_leaderboard_entry_type
        if self.public_description != None:
            body['public_description'] = self.public_description
        if self.restrict_commenting != None:
            body['restrict_commenting'] = self.restrict_commenting
        if self.restrict_posting != None:
            body['restrict_posting'] = self.restrict_posting
        if self.show_media != None:
            body['show_media'] = self.show_media
        if self.show_media_preview != None:
            body['show_media_preview'] = self.show_media_preview
        if self.spam_comments != None:
            body['spam_comments'] = self.spam_comments
        if self.spam_links != None:
            body['spam_links'] = self.spam_links
        if self.spam_selfposts != None:
            body['spam_selfposts'] = self.spam_selfposts
        if self.spoilers_enabled != None:
            body['spoilers_enabled'] = self.spoilers_enabled
        if self.sr != None:
            body['sr'] = self.sr
        if self.submit_link_label != None:
            body['submit_link_label'] = self.submit_link_label
        if self.submit_text != None:
            body['submit_text'] = self.submit_text
        if self.submit_text_label != None:
            body['submit_text_label'] = self.submit_text_label
        if self.suggested_comment_sort != None:
            body['suggested_comment_sort'] = self.suggested_comment_sort
        if self.title != None:
            body['title'] = self.title
        if self.toxicity_threshold_chat_level != None:
            body['toxicity_threshold_chat_level'] = self.toxicity_threshold_chat_level
        if self.type != None:
            body['type'] = self.type
        if self.user_flair_pns_enabled != None:
            body['user_flair_pns_enabled'] = self.user_flair_pns_enabled
        if self.welcome_message_enabled != None:
            body['welcome_message_enabled'] = self.welcome_message_enabled
        if self.welcome_message_text != None:
            body['welcome_message_text'] = self.welcome_message_text
        if self.wiki_edit_age != None:
            body['wiki_edit_age'] = self.wiki_edit_age
        if self.wiki_edit_karma != None:
            body['wiki_edit_karma'] = self.wiki_edit_karma
        if self.wikimode != None:
            body['wikimode'] = self.wikimode
        if self.op != None:
            body['op'] = self.op
        if self.reason != None:
            body['reason'] = self.reason
        if self.stylesheet_contents != None:
            body['stylesheet_contents'] = self.stylesheet_contents
        return body


    def clear_queries(self):

        self.after = None
        self.before = None
        self.count = None
        self.limit = None
        self.show = None
        self.sr_detail = None
        self.user = None
        self.uh_x_modhash_header = None
        self.api_type = 'json'
        self.img_name = None
        self.omit = None
        self.over_18 = None
        self.srnames = None
        self.include_over_18 = None
        self.include_unadvertisable = None
        self.query = None
        self.search_query_id = None
        self.typehead_active = None
        self.exact = None
        self.admin_override_spam_comments = None
        self.admin_override_spam_links = None
        self.admin_override_spam_selfposts = None
        self.all_original_content = None
        self.allow_chat_post_creation = None
        self.allow_discovery = None
        self.allow_galleries = None
        self.allow_images = None
        self.allow_polls = None
        self.allow_post_crossposts = None
        self.allow_predictions = None
        self.allow_predictions_tournaments = None
        self.allow_top = None
        self.allow_videos = None
        self.api_type = None
        self.automated_reporting_level_abuse = None
        self.automated_reporting_level_hate = None
        self.collapse_deleted_comments = None
        self.comment_score_hide_mins = None
        self.crowd_control_chat_level = None
        self.crowd_control_level = None
        self.crowd_control_mode = None
        self.description = None
        self.disable_contributor_requests = None
        self.exclude_banned_modqueue = None
        self.free_form_reports = None
        self.g_recaptcha_response = None
        self.header_title = None
        self.hide_ads = None
        self.key_color = None
        self.lang = None
        self.link_type = None
        self.name = None
        self.new_pinned_post_pns_enabled = None
        self.original_content_tag_enabled = None
        self.over_18 = None
        self.prediction_leaderboard_entry_type = None
        self.public_description = None
        self.restrict_commenting = None
        self.restrict_posting = None
        self.show_media = None
        self.show_media_preview = None
        self.spam_comments = None
        self.spam_links = None
        self.spam_selfposts = None
        self.spoilers_enabled = None
        self.sr = None
        self.submit_link_label = None
        self.submit_text = None
        self.submit_text_label = None
        self.suggested_comment_sort = None
        self.title = None
        self.toxicity_threshold_chat_level = None
        self.type = None
        self.user_flair_pns_enabled = None
        self.welcome_message_enabled = None
        self.welcome_message_text = None
        self.wiki_edit_age = None
        self.wiki_edit_karma = None
        self.wikimode = None
        self.op = None
        self.reason = None
        self.stylesheet_contents = None